version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: awsdevopsharsha/mysql:v2
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: awsdevopsharsha/backend:v2
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: awsdevopsharsha/frontend:v2
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend